name: Build and Publish Packaged Release

on:
  push:
    branches: [ PKCE ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish-new-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@OWNER"

      - name: Install NPM modules
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Package NPM Module
        run: npm run build

      - name: Publish to Package Repository
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd ./dist && echo "registry=https://npm.pkg.github.com/clinical-cloud" >> ./.npmrc && npm publish
